name: air-quality

services:
  ui:
    image: agoenk/ui_aq:latest  # <--- GANTI INI JADI NAMA USER KAMU LANGSUNG
    ports:
      - "8501:8501"
    volumes:
      - ./config:/home/config
    depends_on:
      - api


  api:
    image: agoenk/api_aq:latest
    ports:
      - "8080:8080"