name: air-quality
services:
  ui:
    # build:              # <-- Kasih pagar
    #   context: .        # <-- Kasih pagar juga
    #   dockerfile: ./docker/ui/Dockerfile # <-- Kasih pagar juga
    image: agoenk/ui_aq:latest
    depends_on:
      - api
    ports:
      - "8501:8501"

  api:
    # build:              # <-- Kasih pagar
    #   context: .        # <-- Kasih pagar juga
    #   dockerfile: ./docker/api/Dockerfile # <-- Kasih pagar juga
    image: agoenk/api_aq:latest
    ports:
      - "8080:8080"