name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Login to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Docker Compose Build and Push
      run: |
        docker compose build
        docker compose push
  
  docker-pull-ec2:
    needs: docker-compose-build
    runs-on: ubuntu-latest
    steps:
    - name: Creating SSH Configuration File
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deployment.pem
        chmod 600 ~/.ssh/deployment.pem
        cat >> ~/.ssh/config <<END
        Host deploy_ec2
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deployment.pem
          StrictHostKeyChecking no
        END
    - name: Deploy to EC2
      run: |
        ssh deploy_ec2 << EOF
          # 1. Hapus dan download ulang file
          rm -f docker-compose.yaml
          wget https://raw.githubusercontent.com/agungwahyuprayogo/air_quality/refs/heads/master/docker-compose.yaml
          
          # 2. Panggil docker dengan path lengkapnya secara langsung
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | sudo /usr/bin/docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
          sudo /usr/bin/docker compose pull
          sudo /usr/bin/docker compose up -d
        EOF
